test1-job:
  only:
  - master
  tags:
  - web-server
  
  script:
  - echo "WebServer CI Start"
  - docker build -t 192.168.1.99:5000/web .
  - docker push 192.168.1.99:5000/web
  - ssh manager docker service create --name web -p 80:80 --replicas 4 192.168.1.99:5000/web
